const Sequelize = require('sequelize')

module.exports = (sequelize, DataTypes) => {
    return sequelize.define('RecibosDetalle', {
      id: {type: Sequelize.UUID, primaryKey: true},
      idEmpresa: Sequelize.INTEGER,
      idRecibo: Sequelize.INTEGER,
      iLinea: Sequelize.INTEGER,
      rImpRecibo: Sequelize.REAL,
      fRecibo: Sequelize.DATE,
      idCliente: Sequelize.INTEGER,
      idMoneda: Sequelize.INTEGER,
      fCarga: Sequelize.DATE,
      rDisponible: Sequelize.REAL,
      rCambio: Sequelize.REAL,
      bAnulado: Sequelize.BOOLEAN,
      idMonedaReferencia: Sequelize.INTEGER,
      rCambioReferencia: Sequelize.INTEGER,
      iTipo: Sequelize.INTEGER,
      cImporte: Sequelize.REAL,
      idBanco: Sequelize.INTEGER,
      sNumCheque: Sequelize.STRING,
      idTarjeta: Sequelize.INTEGER,
      sNumeroCuenta: Sequelize.STRING,
      idLoteCupon: Sequelize.INTEGER,
      idCupon: Sequelize.INTEGER,
      idClienteRetencion: Sequelize.INTEGER,
      idPvRetencion: Sequelize.INTEGER,
      idNumDocRetencion: Sequelize.INTEGER,
      idImpuestoRetencion: Sequelize.UUID,
      idTransferenciaBanco: Sequelize.UUID,
      idTipoDoc: Sequelize.STRING,
      idProveedor: Sequelize.INTEGER,
      idNumDoc: Sequelize.INTEGER,
      idDepositoBanco: Sequelize.UUID,
      InsertedOn: Sequelize.DATE,
      UpdatedOn: Sequelize.DATE,
      DeletedOn: Sequelize.DATE,
      bAlDia: Sequelize.INTEGER,
      bDiferido: Sequelize.INTEGER,
      fVencimiento: Sequelize.DATE,
      reciboid: Sequelize.UUID,
      idRefNumDoc: Sequelize.INTEGER,
      idRefPv: Sequelize.INTEGER,
      idRefTipoDoc: Sequelize.STRING,
      idVendedor: Sequelize.INTEGER,
      sNumTransferencia: Sequelize.STRING,
      DownloadedAt: Sequelize.DATE,
      }, {
        timestamps: false,
        paranoid: true,
        freezeTableName: true,
        tableName: 'RecibosDetalle',
        hasTrigger: true
      })
}